### ISSUE TITLE
<CairoContext> from 'draw' signal should not free the context

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#100]
It appears that in a `GtkWidget` _draw_ signal handler, the `cairo_t` that is referenced in the `<CairoContext>` that is generated needs an additional  `cairo_reference` so that it is not freed when `<CairoContext>` is garbage collected, since that `cairo_t` is owned by the `GtkWidget`.
If a GC occurs during the _draw_ signal, it will hit the
```
CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)
```
in `cairo_destroy`

This script demonstrates the bug [cairo-bug.scm.txt](https://github.com/spk121/guile-gi/files/5482575/cairo-bug.scm.txt)

**Comment by spk121** [comment]
Could be that in `gig_value_to_scm_structured_type`, boxed types are always copied as `GI_TRANSFER_EVERYTHING` unless they are GValue or string

**Comment by LordYuuma** [comment]
That certainly stands out in this file when everything else is transfered with `NOTHING`. Is there a reason for this?
