### ISSUE TITLE
HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by laodzu** [spk121/guile-gi#101]
Trying to do a fresh build I cannot get past step 0:

dzu@krikkit:/opt/src/git/guile-gi (master)$ ./bootstrap 
+ exec autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:42: installing 'build-aux/compile'
configure.ac:25: installing 'build-aux/missing'
Makefile.am:240: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
Makefile.am: installing 'build-aux/depcomp'
autoreconf: automake failed with exit status: 1
dzu@krikkit:/opt/src/git/guile-gi (master)$ 

What am I doing wrong?

Thanks in advance!
  Detlev

**Comment by spk121** [comment]
On Fedora, the file you are missing `/usr/share/aclocal/introspection.m4` is provided by the package `gobject-introspection-devel`

**Comment by laodzu** [comment]
Excellent, thanks.  On Debian bullseye that's just "gobject-introspection".

One step closer but not still there:

dzu@krikkit:/opt/src/git/guile-gi (master)$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for ar... ar
checking the archiver (ar) interface... ar
./configure: line 4271: syntax error near unexpected token `3.0'
./configure: line 4271: `GUILE_PKG(3.0 2.2)'
dzu@krikkit:/opt/src/git/guile-gi (master)$

I have guile compiled and installed from git master.

Sorry for those stupid questions...

**Comment by spk121** [comment]
Do you have the file `/usr/share/aclocal/guile.m4` installed?
It may be that you are missing the Debian analog for `guile-3.0-dev` or `guile-devel`

**Comment by laodzu** [comment]
I do have it in /usr/local/share/aclocal from my local install from git:

dzu@krikkit:/opt/src/git/guile-gi (master)$ ls -l /usr/local/share/aclocal/guile.m4
-rw-r--r-- 1 root root 15726  9. Nov 22:34 /usr/local/share/aclocal/guile.m4
dzu@krikkit:/opt/src/git/guile-gi (master)$

**Comment by laodzu** [comment]
The lines in configure starting with line 4270 are:

# from guile.m4
GUILE_PKG(3.0 2.2)
GUILE_PROGS
GUILE_FLAGS
GUILE_SITE_DIR

So it seems guile.m4 got picked up.

**Comment by laodzu** [comment]
Urgh.  I am not able to prevent that comment sign being picked up by the markdown renderer....

**Comment by spk121** [comment]
Likely, you have failed to include `/usr/local/share/aclocal` in your `ACLOCAL_PATH`.
Try running as `ACLOCAL_PATH=/usr/local/share/aclocal ./bootstrap`
If that works, you'll probably have other environment variables you'll need to make sure are correct: `LD_LIBRARY_PATH` and so on

**Comment by laodzu** [comment]
Ok, thanks.  Another step.  Finally I had to install "libgirepository1.0-dev" which seems to be somehow equivalent to "gobject-introspection-devel" (<irony>how could I not know this!</irony>) and now compilation works.  LD_LIBRARY_PATH already included the /usr/local stuff without any special setup from my side.  I really do wonder why ACLOCAL_PATH requires this special treatment.

Maybe it is not so common anymore to build packages from source outside package management and install it into /usr/local?

Anyway, thanks for solving my problems!
