### ISSUE TITLE
Unicode mishap in test/string.scm

### ISSUE THREAD

**Issue by ghost** [spk121/guile-gi#112]
Hello,

The new guile reader chokes on test/string.scm, because it contains ◌̀ (dotted circle U+25cc, followed by grave accent U+0300). In guile 3.0.2, the reader just ignored the dotted circle, but in guile 3.0.7 this bug is fixed.

https://issues.guix.gnu.org/51447

**Comment by considernotgithub** [comment]
You can fix it with the following patch:

[0001-Fix-a-reader-failure-with-3.0.7.zip](https://github.com/spk121/guile-gi/files/7467074/0001-Fix-a-reader-failure-with-3.0.7.zip)

**Comment by spk121** [comment]
Thanks for the report
