### ISSUE TITLE
Implement GOOPS-like OOP stuff

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#13]
In short, let us be able to write stuff like

    (define-method (method (obj <GtkWidget>)) ...)
    (method (create <GtkWindow>))

Internally, we might use GOOPS (it appears we already do to some extent, see `SCM_INSTANCEP`) or we might implement our own stuff on top of `gtype-is-a?`. It seems we only need to get class inheritance right, is there a way to do this for foreign types?

**Comment by LordYuuma** [comment]
After some research I found out, that foreign objects are implemented on top of GOOPS, which is why `SCM_INSTANCEP`, `SCM_CLASS_OF`, etc. work as they do. Therefore we may either
- try to hack superclasses into the CPL somehow, or
- construct our own "foreign-object" of sorts, which allows inheritance. Specifically the interface would be something like `(make-gobject-class type parent interfaces)` (name pending), and perhaps we should extend `register-type` to also take interfaces into account.

It also appears as if we're not using finalizers (when do our objects get deallocated then?). Since GObject has `g_object_unref`, we may however just wrap objects in SCM pointers with unref as finalizer and construct SCM objects around them if finalizing becomes necessary at some point.

**Comment by spk121** [comment]
Merging these GObject pseudo-classes into true GOOPS classes would bring many advantages, though I haven't thought through the design details beyond using GOOPS-friendly foreign objects.  The current hack of storing all the methods in a GLib hash-table of hash-tables was always a minimum-viable-product strategy.   Although, whenever I speak of GOOPS to the Guile community at large, there are many naysayers.

**Comment by LordYuuma** [comment]
Most of the benefits will be internal (such as for instance being able to determine whether a Scheme object is a GObject and an object's type without making a hash lookup).  I don't think the naysayers will have complaints about that, just like they will probably use foreign objects themselves until you tell them they were GOOPS all along.

There does come one big disadvantage with just making classes GOOPS-friendly and that is, that we're not quite GOOPS. For instance, our `create` and their `make` are incompatible, but too much similarity would invite people to (wrongfully) use `make` (or any other GOOPS functionality) where it is not supported by us. The same would hold e.g. for extending types. And realistically speaking, we will always have to hide at least properties and signals...

Or perhaps not. Properties could be applicable structs with setters and signals could be applicable structs. The actual property would still only exist in the GObject pointed towards, but this distinction would make it less likely that someone would want to instantiate them with `make` rather than `create`. (Adding the benefit, that we could still `make` a GObject that we got through other means, e.g. manually written FFI functions in cases where the typelib is broken).

I'm still having thoughts about some other design details, but for now let's hear some of your questions.

**Comment by LordYuuma** [comment]
Yay, we've got GOOPS-based properties on our dev-branch. Next will be GOOPS-based signals (do we already have a way to emit signals?) and then we'll make GOOPS-based types.

As far as types are concerned, I'd do the following: We define a `<GObject>` type with more or less the same slots that we currently use in `gir_type`. (Perhaps we should also add a basetype for interfaces.) This has to be done manually, there's no way around that. When we define objects types from typelibs, we define a new GOOPS type with the parent type and the implemented interfaces as direct supertypes. When we define an interface type, we define a GOOPS type with all prerequisites as direct supertypes.

Up until now, we should still be able to use our `call-method` hash stuff. The next step would then be to wrap methods in GOOPS methods. At the same time, we can also put properties and signals into generics (they are already applicable structs, but they are not bound to any type – this is preferable, because it allows us to use them while defining types). Finally, after all that is done `(foo obj-a)`might be a property getter for "foo" of some object of Type A, whereas `(foo obj-b)` invokes the `foo` method of some object of Type B with 0 additional arguments. At this point we would no longer need any wrappers à la `with-object` or #12 and there'd be no conflicts with anything because of generics.

Note: `connect` would be defined as `(connect (obj <GObject>) (sig <signal>) (proc <procedure>))`, and so on.

**Comment by spk121** [comment]
Haven't looked at it yet, but, sweet!  There is no `emit-signal` function yet.

**Comment by LordYuuma** [comment]
Signals work now as well. There are some things, that I'd like to change about the way they do, but that will probably have to wait until we've converted our types. Specifically, I'd like our signal and property primitives to operate on signal and property objects, if that is possible.

Anyway, let's talk about types, because I already fear the merge/rebase with #15. There have been lots of references, especially unsafe ones, to slots of a type that we're not even instantiating (see 926632a). In fact, I've defined some macros, just so that I don't have to edit all these references. Of course, better encapsulation will be needed. In any case, I was asking myself where we would put the code for the new object type. It seems `gi_gobject` would be the better place and in `gir_type` we'd only make references to it. What do you think, where to make the split?

**Comment by spk121** [comment]
OK.  All those slots comes from how things are done in the Python GObject binding.  I put them in because that's how python did it, thinking that some day it might be important to understand how PyGObject uses them, but, obviously no one has touched any of that code ever since. The python model used the refcount slot and the weak references for Python-side garbage collection, and the dictionary type for storage of object properties in the object.  Two curious uses of the flags parameter in Python was to denote GObjects stored on the stack vs heap, and dealing with `GInitiallyUnowned`.  Hopefully we never have to deal with that here.

guile-gi's actual garbage collection strategy for object will probably just be to take advantage of `g_object_ref` and `g_objet_unref`, increasing references if objects are passed as arguments, and decreasing references as objects are garbage collected.  But other bindings seem to add additional strategies, so maybe the simple ref/unref is harder to get right than it appears.

In terms of naming and prefixes, some files are `gi_` and some are `gir_` apparently randomly.  This is another vestige from python: mimicking Python's 'pyg' for code having to do with the object type, and `py_` for everything else. This division of labor hasn't been very useful or clear, so in the future, I'd rather go with `gir_` for everything going forward, since `gi_` is already used.

But as to your `gi_gobject` and `gir_type` question, I'd start with a new `gir_object` file. haha.

But, as I think you were suggesting, you could keep `gir_type` as the place where you keep a mapping between `GType` integers and classes, while defining those classes elsewhere, which seems sensible.

**Comment by spk121** [comment]
As far as the rebase, I think it would be easier to push this work first, and then #15 (or a cleaner attempt of the same) can be put on top.

**Comment by LordYuuma** [comment]
I don't think reference handling should be too complicated beyond `ref` and `unref`. Looking at Vala, the only thing that is slightly confusing are floating references, where we should `ref_sink` instead. There are some typelibs (or at least vapis) which don't annotate those correctly, but if we go by a "we don't know, so let's just check" approach, everything should be fine.

I think we should be able to have a GObject type with a single slot, that slot being a pointer to the actual object, of course wrapped in a pointer object. This slot should be protected in some way against direct access. (Or should it? Not doing so would – while being discouraged, of course – allow users to directly use the same functions from Guile's FFI, which is dangerous, but could be used as a means to work around broken typelibs.)

In terms of naming, we should consider a big round of refactoring after everything is merged to master. I'd rather not have too many feature branches open while we're doing that, for obvious reasons. To be quite honest, both `gi` and `gir` sound equally misleading on top, standing for "GObject Introspection" and "GObject Introspection Repository" respectively. How about `gig` for "GObject Introspection + Guile"? (It sounds better than `gug`, `gugi` and `ggi`) On the Scheme side, we will of course still claim the `gi` namespace.

**Comment by spk121** [comment]
Yeah, `gig` is fine.

If the goal is to go with a single pointer containing a GObject, where will the old `inst_dict` instance dictionary for holding Guile-specified GObject property values go?

**Comment by LordYuuma** [comment]
I thought, that could be a slot called "obarray", but it didn't seem quite right, and the reason for that is, that we currently have circular references. SCM objects wrap GObjects, which themselves refer to the object that wrap them? Seems like it would break stuff badly if we somehow constructed a different reference to the same GObject. Instead, we could use the SCM hash table directly, or use a GValue array/hash (since everything is a GValue anyway and the indices are uints).

**Comment by spk121** [comment]
OK. I finally had a moment to read through all this.  You are a good coder.  You know your stuff, both on the Scheme and the C side, which is rare.

I we're really, really going down this GOOPS rabbit hole, then I think we've got to be all in. (You've already overloaded `connect`, so I guess we're all in already.)  The part that would be most satisfying would be deprecating `with-object` as a new syntax that users have to learn. Expressing all the introspected functions and methods via `define-method`.  So I think what that also means is that as the introspected GObject classes are loaded from the typelib, their GOOPS classes are created, and the GOOPS class inheritance should match the GObject class inheritance, building up a class tower.  This would have the advantage of allowing the current method-resolution logic (and the hash-of-hashes where the methods are currently stored) be eliminated, relying on GOOPS to figure out which function/method to call for a given set of parameters.  Hopefully eliminating more guile-gi code.

In any case, if you feel good about what you have here, the time has come to push this branch to master, so other work can rebaseline off of it.

**Comment by LordYuuma** [comment]
Thanks for the compliment.

Oh, I do plan to go all in. I'm currently working on the type defines, breaking about half of our testcases as I do so. And wouldn't you know it, I found out that we're using the same code for GObject and GBoxed, which is baaaaaaaad.
As far as `define-method`ing method is concerned: That's the plan, but we have to "reimplement" define-method in C :)

You can pull this to master if you want. It's not *that* useful yet, and there's some undocumented interface breakage, but it's significantly less breakage than what I've got locally as of right now.

**Comment by LordYuuma** [comment]
Methods are kinda implemented on the `dev-oop` branch now, but it's still largely WIP. Since names have become shorter, they're kinda overlapping with everything else, including our own convenience functions, so we'll need to tweak some interfaces after that.

**Comment by LordYuuma** [comment]
About the naming question: It might not be a bad idea to define methods twice, once with pseudo-namespace and once without. What do you think?

**Comment by spk121** [comment]
That would be fine.  Anyone coming to this from Gtk C would probably find it more familier, TBH.  But, playing devil's advocate, why wouldn't it be sufficient to use #:prefix and #:renamer?

**Comment by LordYuuma** [comment]
Because scoping. We have a module per typelib, not a module per class, meaning `gtk:get-parent` would bind every `get-parent` method in Gtk, rather than say `gtk_widget_get_parent`, which would get the pseudo-namespaced `widget:get-parent` when defined normally as a function.

We could of course also define all methods with full names and have the users rename them in post. However, I don't think many want to know exactly where these functions are defined, given that they don't need to know when using Vala, <insert non-C-lang here>, guile-gnome or earlier versions of this library. Perhaps we could mitigate this somewhat by allowing them to explicitly merge generics, such as `(using gtk:widget)` to flatten everything that has the gtk:widget prefix or `(use-generic get-parent show hide)`. When doing things this way, renamers would not be strong enough, because they can't merge generics.

That's not to say, that `#:prefix` and `#:renamer` can't work to fix other issues, e.g. conflicting init funcions in Gtk and Grl, but in this instance we also have to find a way to attach meaning to the symbols that they bind.

**Comment by spk121** [comment]
OK. I see what you mean now.  In the python binding they have a similar idea where, in many cases, you can call `method` or if you want to be more precise, you can call `class:method`.
And I'm definitely *not* arguing for c-style names or longer names in general.

**Comment by LordYuuma** [comment]
TBH, Python is a fairly weird language with object methods basically being syntactic sugar for `cute`.  Anyway, we have methods on "both scopes" now, even though they work exactly the same because we aren't Python and need no fancy syntax for that :)

With that said, we are on a good way to march towards our goal, we're only lacking signal and property support in the generics (and we need to figure out how to handle functions defined in multiple typelibs – ideally, we should only have to enable generic merging). Once I've figured that out, this issue is finally resolved. 075f432 is a good commit for merging and trying stuff out, although it does cause some warnings here and there.

**Comment by spk121** [comment]
While trying to port over the code in the examples directory, I do see some of the disadvantages of letting introspection overload commonly used procedures and syntax.  It took me a bit to figure out that one error was caused by overloading `receive`.  If we go with the strategy that each function or method has a short name (`run`) and a long name (`application:run`), then we could maintain a list of short names that are too important to overload, e.g. `receive`, `define`.  Introspected short names that conflict could be imported as something like `_receive`, `receive_`, `$receive`, `»receive`, `:receive`, `関数receive` ;-)

**Comment by LordYuuma** [comment]
Can you push some breaking testcases to `dev-oop`, ideally one per conflict? I think the bug might be caused by overriding syntax, so I obviously tend to `関数receive` :)
JK, we should probably use `-receive` or `%receive`.

**Comment by LordYuuma** [comment]
I see now, you're talking about the editor example. Sadly, that one is broken in more ways than just one. We're also handlling boxed types incorrectly, meaning we need handle (and test) them as well. i've fixed the other examples on master, but this will need some work.

As far as the static list is concerned, I'm not sure. I think, we should rather differentiate using other criteria, if possible. At worst, we have to define a renamer. Speaking of which...

**Comment by LordYuuma** [comment]
Editor example is fixed now and docs are updated.

**Comment by spk121** [comment]
This is really nice.  The examples look very readable.  I think the time has come to close out this general issue and work future corrections as their own issues.  I'm going to pull this tree into master and then begin applying the renaming patches on top of it.

**Comment by spk121** [comment]
Closed with PR #20
