### ISSUE TITLE
Compute array length arguments

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#15]
Some procedures created by introspection have pairs of arguments that are a pointer to a C array and an associated C array length, such as `argc` and `argv`  The scheme wrapper should compute both C arguments from a single SCM list or vector.

 The `g_type_info_get_array_length` procedure can be used to identify these arguments.

**Comment by LordYuuma** [comment]
Added bug label, because the current method of finding array lengths returns wrong results in this case.

**Comment by spk121** [comment]
in f009e149abf52d2c7476950f6042d9a0e9f8b999 I have outlined a solution
In f009e149abf52d2c7476950f6042d9a0e9f8b999 you can see how some of the tests change

 But, still needs a big clean up
- I want to use ssize_t everywhere for array sizes. Now it is a mix of int, size_t, and ssize_t.
- memory leaks
 - I used -1 in many places to mean unknown size, which could be improved

**Comment by LordYuuma** [comment]
I think we should use `size_t` (or `gsize`) rather than `ssize_t`. Sizes will always be positive. The only instance where we need to use signed sizes are relative offsets, e.g. when dealing with SCM vectors.

When do the memory leaks occur? If it has to do with error handling, try sprinkling some `scm_dynwind`s around, that always helps me.

-1 is a "good" error value, we will rarely have an array that large. But you're right, we should signal an error there in some better way.

**Comment by spk121** [comment]
Yeah, I should lean heavier on `scm_dynwind`  It is super effective.

The main memory management problem is in C->SCM argument conversions.  The C arguments may need to be freed, situationally.  There is some scaffolding for solving the problem. The introspection library provides guidance with `GITransfer` and there is an old attempt at solving the problem with `gi_giargument_free_args`.  It just needs to be fixed.

**Comment by LordYuuma** [comment]
I think it would help, if you add the `GITransfer` to the arg map entries. Then you could have a free func, which depends only on the type and the map entry (which uses the GITransfer field along with the array length if needed for an array)

**Comment by spk121** [comment]
The commit bd6a99472daa844bf3cd623bdef9c3ea39413f4f fixes part of this problem.

As it turns out, there are also return values which are pointer to arrays whose sizes are output arguments, which is not accounted for here. See `g_application_command_line_get_arguments` for example.

**Comment by LordYuuma** [comment]
So what we do have right now is

    /* works */ 
    void foo(char **out_array, int *out_array_size);
    /* doesn't work */
    char **bar(int *bar_size);

am I right? Which would mean, we also have to pass the arg map to the return value handling stuff. (Generally speaking, we should have a more uniform handling of out arguments and return values. Why are they even different in the first place?)

**Comment by spk121** [comment]
That's right. They were different because arguments information is given as GIArgInfo while return value information is given as the less informative GITypeInfo plus the strings returned by `g_callable_info_iterate_return_attributes`.  It is the information in `g_callaable_info_iterate_return_attributes` that can be used to augment the missing information in the `GITypeInfo` to make it more or less equivalent to a `GIArgInfo`, but, that work hasn't happened.  For v0.0.1, parsing only GITypeInfo was enough to get most of the procedures working.

**Comment by spk121** [comment]
Well I had made the assumption that when you see something like `[array length=argc]` in the documentation of a return value, that I would be able to introspect that information in the return attributes, but, I can't seem to find a way to do that for return values.  For the case ...
```
/* doesn't work */
char **bar(int *bar_size);
```
... I'll just have to return a pointer.  I scanned through the *.gir files and that information doesn't seem to be there for return values. So, I guess I'm done with this bug.

See 2b2f898d279687a83d371150e449ffda33f311e3

**Comment by LordYuuma** [comment]
I'm not sure about other attributes, but we should at least be able to figure out the length. After all, we do have

    gint g_type_info_get_array_length (GITypeInfo *info);
    gint g_type_info_get_array_fixed_size (GITypeInfo *info);

both of which operate on TypeInfos rather than ArgInfos. And since ArgMapEntries don't reference ArgInfos, we should be able to construct them for the return argument as well, shouldn't we?

**Comment by spk121** [comment]
That works.

**Comment by LordYuuma** [comment]
"That works" as in "that works theoretically" or as in "our code already does that"?

**Comment by spk121** [comment]
I check it enough to prove that it will work on the next commit. :-)

**Comment by spk121** [comment]
OK. Fixed in e815d027545c258702555406569b3eda6d9b5a90
I'll push it to master as soon as I clean up a couple more things.

**Comment by spk121** [comment]
Merged to master
