### ISSUE TITLE
Improve GObject enum representation

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#33]
The  enum feature in core Guile is in `(rnrs enums (6))` which seems to be commonly implemented in various Schemes, if seldom used.  It may be useful to use these enums to group the GObject enums generated by introspection.

**Comment by LordYuuma** [comment]
While I'd like to do something similar as well, there are a number of issues with R6RS enums.
1. They are not GOOPS classes and hence incompatible with GOOPS. You can define `(frob (<integer>))` but not `(frob (<enum>))`.
2. There is (as far as I know) no straightforward way to assign symbols to enum values. With GOOPS classes, we can have a class-allocated obarray to perform this lookup.
3. The printer for enum sets is horrible. I would very much like to know the value of my enums.

We sadly can't extend any base types (integers, lists...) using GOOPS. I think our best bet is to extend `<GFundamental>` and repurpose `ptr` (maybe call it `value` instead?), then implement conversion to/from R6RS enums.

**Comment by spk121** [comment]
OK.  How about this... When implementing our enum types, let's try to recreate the API provided by r6rs enums on top of our fundamentals.

**Comment by LordYuuma** [comment]
Sounds reasonable, I guess, although only flags are really expressed as sets. Given this difference, I was rather thinking of

    (enum->number enum)
    (enum->symbol enum)
    (number->enum number type)
    (symbol->enum symbol type)
    (number->ENUM_TYPE number)
    (symbol->ENUM_TYPE symbol)

    (flags->list flags)
    (list->flags list type)
    (list->FLAGS_TYPE list)
    (flags-set? flags symbol-or-list)

among maybe some others.

**Comment by LordYuuma** [comment]
> ```
> (enum->number enum)
> (enum->symbol enum)
> (number->enum number type)
> (symbol->enum symbol type)
> (number->ENUM_TYPE number)
> (symbol->ENUM_TYPE symbol)
> 
> (flags->list flags)
> (list->flags list type)
> (list->FLAGS_TYPE list)
> ```
should be implemented now, but with type as the first argument for better currying. `flags-set?` is still missing, although it should be a trivial addition. The current internal represantation is symbols/lists, but since all that logic is implemented in scheme, we should easily be able to make it numbers instead. (And perhaps numbers would be better, though I'm not sure).

**Comment by LordYuuma** [comment]
After some automake weirdness and rebasing, I've finally figured out, how not to break the tests. Yay.

In other news, I believe my implementation of enums and flags to be "complete", at least w.r.t. this issue.
