### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#34]
We've cleared all milestones so far set for 0.1. Now let's write some NEWS and tag a "proper" release.

**Comment by spk121** [comment]
Tagged in aaa6c98e8a74c56b1583b6f03dd3a4da89506895

**Comment by LordYuuma** [comment]
Nice.

**Comment by spk121** [comment]
Email sent to guile-user.

GNU friendly, no-javascript-required tarball uploaded to http://lonelycactus.com/tarball/guile_gi-0.1.0.tar.gz
