### ISSUE TITLE
Output and inout args, bytevectors, and `set!` procedures

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#40]
There are a couple of SCM types that are amenable to being modified in place during a call to C procedures: bytevectors and hash tables, for example, and there are some introspection functions that expect to modify a variable in place.

For example, `g_io_channel_read_chars` expects a C `gchar` buffer to be modified in place.  For this, we could require a bytevector input and modify it in place.

Procedures that do this could perhaps have a `!` sigil.

Alternately, we can avoid modifying input parameters.  Perhaps the metadata supplies enough information to identify them, and then we'll pass new copied-and-modified  (or copy-on-write) variables as output parameters.

**Comment by LordYuuma** [comment]
Isn't this exactly #39?

**Comment by spk121** [comment]
At the time I originally opened this, I had a reason why this wasn't exactly the same as #39
But I've forgotten the nuance I was trying to describe, so, I'll just close this as duplicate.
