### ISSUE TITLE
Find a way to handle non-GTyped structs

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#43]
Non-GType structs are awful to handle. Not only is nothing related to them and their methods exported from `gig_repository`, they also resolve to G_TYPE_NONE when given as arguments or return. At best, this leads to meaningless behaviour, such as `(define-values () (repository:require self namespace- version flags))`. At worst, we're actively contributing to errors, perhaps even crashes.

Given that we already had similar problems with flags, perhaps it's time to rethink part of `gig_type`. We should keep GType associations as they are, but perhaps we can find some mapping from GITypeInfos to SCM types, that does not rely on registration with the GType mechanism.

**Comment by spk121** [comment]
Why handle them at all?  Non-GType structures are a failure of upstream to provide proper introspection information.  It would be better to leave that as an upstream concern, and reject any handling of non-GType structures and any functions that use them.

**Comment by LordYuuma** [comment]
As far as I can see, GObject Type Information (i.e. GType, GTypeClass, etc.) and GObject Introspection are two very different kinds of beasts. For the most part, we use the former and rely on the latter only to load shared libraries and give us some GTypes. (This is somewhat simplified. GObject Type Information for instance does not tell us an object's methods.)

Looking at the current state of GIRepository, it does not seem as if the support for non-GType structures is a bug. Implementing enums and flags has showed me, how much GObject itself already relies on pure C enums. Generating the documentation for GLib-2.0, e.g., we find 28 classes/structs/whatever that have a GType and 52 untyped enums and flags. Even in GObject-2.0, we have 33:6 instead of 39:0, and that's only counting untyped enums and flags, which I've implemented out of necessity in accordance with #33.

All in all, I believe the scope of GIRepository to be beyond GType. Later versions may be stricter, but I doubt we're getting any of that in 1.xx.

One short-term benefit of handling non-GType structures was also already alluded to in #29. In trying to get things ready for an implementation of `(load <GITypelib>)`, I had to find out, that `GITypelib` actually does not have a GType. While that particular issue could be resolved through other means, having a generic way of handling such structures would also be nice.

Of course, not having a GType remains a serious issue, particularly w.r.t. memory management among others. A large part of this issue will be finding out how to handle that or realising that we have to transfer that responsibilty to the user.

**Comment by spk121** [comment]
If you look especially at the GLib-2.0 un-GTyped structs, they are of no value, if you already have the Guile standard library.  Trying to pull them in is a waste of time and energy.

**Comment by LordYuuma** [comment]
Perhaps this is true for GLib-2.0, but it is not true for GIRepository-2.0, where the GITypelib structure is someting you don't have in Scheme and I doubt this will hold for all other libraries we encounter. If you worry about pulling too much from GLib (and I can understand being worried about loading stuff you don't need), we do have an API for fine-grained loading, that imo should be preferred over `use-typelibs`. `use-typelibs` is for convenience, not efficiency.

**Comment by spk121** [comment]
Back when I first realized that not all structs had GTypes, I did do my own audit of all of the standard libraries: Gtk, Gdk, WebKit2, GLib, and a couple of others.  I convinced myself then that all the non-GType-ed structs were left out *by design*, being too C-like or too difficult for introspection.  Not including them will still give you a full featured stack. Including them is needless.

You give the case of GIRepository-2.0, but, this project, being a Guile binding in C to GIRepository, should not need to introspect GIRepository to extract a information from GIRepository on how to bind the functions provided by GIRepository.

**Comment by LordYuuma** [comment]
I agree with you on the GIRepository thing, GITypelib not having a GType is not easily solved through this. The point of introspecting GIRepository is two-fold: First, I want to discover features, that we haven't yet implemented, but perhaps should. Second, as a user, this offers even more possibities than `(gi repository)` and `(gi documentation)` do out of the box. For instance, I don't think that lookup by error domain is needed (at least not in our core feature set), but someone may want it nonetheless.

I do not believe GTypes having much to do with the difficulty of introspection. At least in the case of enumerations and flags, it much rather seems that introspection is very possible, but given that they are only needed in a few function calls, sometimes even just in one, the designers didn't want to bother with the additional boilerplate, as it was deemed useless.

Even without a GType, GI still resolves fields, methods, etc. unless you explicitly hide them. If a struct was not needed at all for the introspectable part of the public API, it could be hidden from GI in multiple ways (either already be excluded from the gir, or excluded from the typelib). This not being the case indicates, that they are either needed somewhere as argument or return value, or that they were simply "forgotten" – i.e. they shouldn't be part of the introspectable API, but are.

**Comment by spk121** [comment]
For enumerations and flags, punting them to integers and unsigned integers is an easy workaround, but to expand the expectation that guile-gi will intuit the intention of all broken or incomplete API is too much.  Handling non-GTyped structs in guile-gi is a bad idea.  And functions that use non-GTyped structs should not be bound, since they are upstream bugs.

**Comment by LordYuuma** [comment]
In that case, we should put some work into the argument map and type metainfo w.r.t. invalidation. IIRC, we already have some code in gig_function, that aborts, when we encounter an ArgMap, that has been marked invalid. We just need to ensure, that a function, that references such structs in any way will indeed be marked invalid.

As far as enumerations and flags are concerned, I won't revert the work, that has already been put into them. We'd only be putting in extra effort just to have two different APIs, creating the worst possible confusion.

**Comment by spk121** [comment]
Sounds good.
