### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#48]
With the merging of #25 we will have implemented all of the features, that have been scheduled for the 0.2 release. (#24 is actually resolved minus maybe some documentation).

Before this release, let's make sure to check the documentation once again and to update the NEWS file.

**Comment by spk121** [comment]
In the tutorial doc, we should start off very concrete on usage, laying down a best practice, and then add caveats after introducing a best practice.

For example, I'd say that best practice is
- If you are making a single-file script, use `use-typelibs`
- If you are making a multi-module project, define export libraries with `typelib->module`

And then introduce
- If those feel too slow, consider these many alternatives to be more targeted with what you import

**Comment by LordYuuma** [comment]
I agree, that we should lay down a best practice, specifically because I disagree about the best practice with you.

In both simple scripts and multi-file projects, it is usually best to consistently use `use-typelibs` if applicable. If that is too slow, one should consider manual loading instead. Direct use of `typelib->module` is only meaningful in cases where `use-typelibs` falls short, e.g. if you want to import multiple typelibs (e.g. both GTK and GStreamer) into a single module that can used as a dependency in multiple files or when you want to do module reflection. I'll formulate this into man speak later.

**Comment by spk121** [comment]
hehe. That you disagree with me on all things I just take as a given. ;-)  The surprise would be if you agreed with me about something.

Doc looks good.

Testing a few OS+compiler combinations.  Will tag release and make tarballs on Sep 02.

**Comment by LordYuuma** [comment]
Apropos OS+compiler combinations, we should probably update the `guix.scm`. I think some of the build dependencies are no longer needed.

**Comment by spk121** [comment]
I've never managed to make Guix work for me, so the `guix.scm` is a task I'll have to leave to someone else.

**Comment by spk121** [comment]
35a846d4307d9f52b5a5246e4f0e8e611a178bec closes
