### ISSUE TITLE
Merge doc and docs.

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#52]
There really shouldn't be two doc directories. The reason, why we currently have to rely on them is stated in docs/README:
```
My Git host automatically publishes html files in the 'docs'
directory to a website.
```

Perhaps this can be reconfigured on a per-project basis, so that we can build `doc/guile-gi.html` from Automake without needing a local rule. Perhaps this has to be configured for all projects – in that case, doc/html would still be a better choice. And maybe we can even create the documentation through some CI.

**Comment by LordYuuma** [comment]
After looking into Github pages some more, I am shocked by the lack of features that we are able to choose from. But there are ways of solving this without #59 (which does not mean, that #59 isn't the better solution):

1. Use a new repository called guile-gi-docs and configure it to publish from the master branch. Then, set up a make rule/CI, that pushes a freshly built `doc/guile-gi.html` to that repository.
2. Set up this repository to publish from the gh-pages branch and use a similar setup – the difference would be, that you would have to check this repository out twice in different directories.

Admittedly, both are quite weird, but it's the only thing I can think of for now.

**Comment by spk121** [comment]
Yeah, it is pretty basic.  There is another possibility of only have a `docs` directory in a `gh-pages` branch, and then somehow automatically pushing master updates to updates in the `gh-pages` branch.
I think I'd rather wait on #59 
But one small immediate improvement would be to drop the `docs` directory from the `make dist` tarballs.
