### ISSUE TITLE
Implement tests of uncommon struct/union/object types

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#57]
libmarshall includes a few tests for uncommon argument type such as `GValue`, and `GClosure`

**Comment by LordYuuma** [comment]
I've added tests for `GValue` and `GClosure` and also implemented `GValue` arrays as I went on with them.  Are there other "uncommon" types to test, or shall I close this?

**Comment by spk121** [comment]
Great work.  Feel free to close it.
