### ISSUE TITLE
FOSDEM 2020

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#67]
If approved, there will be a session on guile-gi at the FOSDEM 2020 conference in the Minimalistic Languages track either Feb 1 or Feb 2.

Also, there is the GUIX days fringe event on Jan 30th and 31st.

**Comment by LordYuuma** [comment]
Nice, sound like a great opportunity to spread GuileGI to more people. Are there any plans for the presentation yet?

**Comment by spk121** [comment]
I should hear in a week or two if it has been chosen as a topic for a dev room in the main conference.  If it isn't, I'll probably do a presentation at the Guix fringe event.  I think the dev-room talks are 20 or 25 minutes.

For the presentation, I was thinking it might be interesting to talk about the FFI, GC, and class hierarchy strategies guile-gi has, and how the mapping between GObject and Guile abstractions is imperfect, and what strategies are being used to smooth over the differences.

**Comment by LordYuuma** [comment]
So in terms of implementation locations, that would be `gig_type` (with a bit of `gig_object`), `gig_argument` and `gig_value` (perhaps also `gig_function`?). Yeah, that's definitively enough to cover a 20 minute talk.

Talking about `gig_type`, there is some "legacy" SCM API stuff floating around, which very thinly wraps GObject procedures. Should we modernize/clean this up a bit?

**Comment by spk121** [comment]
Aww. Wasn't selected for FOSDEM.  Pity.
