### ISSUE TITLE
Evaluating GIOCondition

### ISSUE THREAD

**Issue by ChrisVine** [spk121/guile-gi#68]
I have been looking into providing some interfaces in guile-a-sync2 for using coroutines with guile-gi.  However I cannot get file descriptor watches to work correctly - the toy code below blows up when a line is entered on the keyboard, with the error "in procedure number->flags: strange flags seem set".  This seems to occur when evaluating the GIOCondition flags upon executing the callback;

```
(use-modules (gi) (gi repository) (gi types) (ice-9 textual-ports))
(use-typelibs (("GLib" "2.0")))
(define ml (main-loop:new #f #f))
(let ((keyboard (open "/dev/tty" O_RDONLY)))
  (unix-fd-add-full PRIORITY_DEFAULT
                            (fileno keyboard)
                            (list->flags <GIOCondition> '(hup in))
                            (lambda args
                              (let ((line get-line))
                                (display line)
                                (newline)
                                #t))
                            #f
                            (lambda _ #f)))
(run ml)
```
A similar issue arises when using GIOChannel's io-add-watch.

Is this a bug in guile-gi or is there a better way to do it?

**Comment by spk121** [comment]
At first glance, it appears to be a sign-extension error in guile-gi

**Comment by spk121** [comment]
ddbc36f925b59bc38d86fcd8c08b0be3b9153afe seems to be the fix.

Then, to get your example to work, I added the following modifications
```
(use-modules (gi) (gi repository) (gi types) (ice-9 textual-ports))
(use-typelibs (("GLib" "2.0")))
(define ml (main-loop:new #f #f))
(let ((keyboard (open "/dev/tty" O_RDONLY)))
  (unix-fd-add-full PRIORITY_DEFAULT
                            (fileno keyboard)
                            (list->flags <GIOCondition> '(hup in))
                            (lambda (fd condition dummy)
                              (let* ((port (dup->inport fd))
                                     (line (get-line port)))
                                (display line)
                                (close port)
                                (newline)
                                #t))
                            #f
                            (lambda _ #f)))
(run ml)
```

But since the bug in that commit seems so fundamental, I'm concerned why it has been working at all.

**Comment by ChrisVine** [comment]
Thanks, that seems to work fine.  The `(let ((line get-line))` in my test case should have been `(let ((line (get-line keyboard)))`, with the port as a closure.  It is not necessary to duplicate the port.

**Comment by ChrisVine** [comment]
Mike, how do I apply g_source_remove to the tag value returned by unix-fd-add-full?  It doesn't seem to be wrapped.

**Comment by spk121** [comment]
It returns #t/#f so it gets bound as a predicate
`remove?` or `source:remove?`

**Comment by ChrisVine** [comment]
`source-remove?` seems to do it.  I was missing the final question mark.  I haven't really got to grips with guile-gi's naming scheme yet (somewhat compounded by the use of GOOPS for class methods): presumably the thinking is that anything returning a gboolean should have the question mark suffix even if the function is run for its side effects.  (The boolean value doesn't mean much here as g_source_remove() always returns TRUE, but naming consistency supports treating it as if it was a predicate I guess.)

**Comment by spk121** [comment]
Yeah, I go back and forth on whether using the predicate naming convention is a dumb idea.  Unfortunately, typelibs don't provide clear information about which procedures have side effects,

**Comment by spk121** [comment]
Fixed by #69

**Comment by LordYuuma** [comment]
Is #69 really related to this?  They look like separate issues to me.

**Comment by spk121** [comment]
It is actually related, because the problem was an uninitialized variable in the callback infrastructure that led to the 'condition' <GIOCondition> being filled with garbage, causing it to have enum values out of the set, and creating the error.

**Comment by LordYuuma** [comment]
Hmm.  I had the impression, that #69 was about arity, in a way you're right, because on the implementation side, both are (un)packing issues.  Speaking of which, we previously did not and currently don't support any pointer or object types in callbacks.  Is there a use-case for this somewhere, so that we can raise an issue about it?
