### ISSUE TITLE
OUT and INOUT parameters in callbacks

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#69]
At the moment, callback procedures do not deal with OUT parameters correctly.  A pointer to an OUT parameter is passed as input in `callback_binding`, and that pointer is never updated after the callback's execution is completed.

To match functionality elsewhere, OUT parameters should not be passed to callbacks.
Also, callbacks should use `values`-style multiple-value return to return all return values, INOUT and OUT parameters.

There are tests in marshall.c that could be used.

**Comment by LordYuuma** [comment]
Is there a way to naively use the procedures from `gig_argument.h` inside `callback_binding`?  It appears as if those conversion methods were once (nearly) identical, but have diverged since.
