### ISSUE TITLE
Evaluating GIOConditon, Part 2

### ISSUE THREAD

**Issue by ChrisVine** [spk121/guile-gi#70]
I cannot seem to reopen issue #68 now it has been closed.  That was fixed by ddbc36f, but is now broken again by #69.  So here is a fresh bug report.  The test case in #68 now fails with:

```
GuileGI:ERROR:src/gig_callback.c:481:amap_entry_to_ffi_type: code should not be reached
Bail out! GuileGI:ERROR:src/gig_callback.c:481:amap_entry_to_ffi_type: code should not be reached
Aborted (core dumped)
```

**Comment by spk121** [comment]
Sorry about that. It should be working again.

**Comment by ChrisVine** [comment]
Thanks, it seems to be working OK now.  There are some interfaces for guile-gi in guile-a-sync2 [here](https://github.com/ChrisVine/guile-a-sync2/tree/master/a-sync): it's not a major thing, but it's there.
