### ISSUE TITLE
Make debug prints more consistent

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#77]
The format of the debug prints should be more consistent with one another.
Also, debug information should tell a useful story about what is going on with the program, and generally should not be cryptic.

**Comment by LordYuuma** [comment]
Do you already have a particular format in mind for that, or perhaps some ideas about what should/should not be printed?

**Comment by spk121** [comment]
I've been playing with debug prints on the dev-debug-print-reorg branch.
In commit f471190676989a0c61c91bcaf964aab8c79eb324 , I was putting the relevant procedure name first, followed by a hyphen.  I think it helps readability.
I also made sure that the function name appears before printing an arg map so that it flows better.

**Comment by LordYuuma** [comment]
Given that we're already fine using hooks, would it make sense to replace some of our debug prints with hooks?  I'm specifically thinking of `c2s`/`s2c` progress report and some transfer stuff.

**Comment by spk121** [comment]
For hoods, I was taking inspiration from the hooks in Guile itself: `%load-hook`, `scm_before_gc_hook`

I think the transfer stuff could fit well into a hook model.  You are advising the user of a specific event that is about to occur or did occur.  And that event does work on the C side so the user's visibility into the event may be limited.

The c2s doesn't fit that model so well the way it is currently implemented, since it is scattered among so many procedures.  It isn't a single event.

In term of utility, though, I find that I'm looking at the C2S prints less and less often now that type conversion is stabilizing.  Maybe we should only conditionally compile them in?

**Comment by LordYuuma** [comment]
I'd strongly prefer conditionally enabling them at runtime, but it
appears we don't have the means to.  `GIG_DOMAIN` is not recognized by
the default logger and we can't handle the `LogField` struct in
Scheme... or can we?
