### ISSUE TITLE
README mentions non-existant "guile-gi" executable

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#80]
Should there be a `guile-gi` executable that gets installed in $(prefix)/bin?

**Comment by LordYuuma** [comment]
No.  The guile-gi scheme modules are all installed in `$prefix/share/guile/$guile-effective-version` and the shared library in `$prefix/lib/guile/$guile-effective-version/extensions` (hopefully, the current guile-gi package seems to not include the "extensions" suffix).  Assuming that these are added to the respective guile paths
```
$ guile
scheme@(guile-user)> ,use (gi)
```
should work just fine – no need to include a workaround for guile-gi specifically.

**Comment by LordYuuma** [comment]
I updated the relevant section in 89dae0879d31ff02d9cf5cce2a8014e282e70984 with some other fixes in-between.
