### ISSUE TITLE
Can't find g_markup_escape_text and g_markup_printf_escaped

### ISSUE THREAD

**Issue by daym** [spk121/guile-gi#91]
Hi,

I can't seem to find `g_markup_escape_text` and `g_markup_printf_escaped` (both in `GLib-2.0.gir`) in `guile-gi`.

It's necessary to use `GtkTreeView`'s `tooltip-column`, because the tooltip text one uses in the tree store column is supposed to be pango markup.

Where is it?

**Comment by LordYuuma** [comment]
`markup-escape-text` should be exported by GLib 2.0. `g_markup_printf_escaped` is likely ignored due to it being a varargs function.

**Comment by daym** [comment]
How do I import the former? I tried

`(use-typelibs (("GLib" "2.0")))` 

where i get

`unknown location: ...: bad use of '...' syntactic keyword in subform ... of ...`, and

and

`(eval-when (compile load eval)
  (require "GObject" "2.0")
  (require "GLib" "2.0")
  ;(require "GdkPixbuf" "2.0")
  (require "Gio" "2.0")
  (require "Gtk" "3.0")
  (load-by-name "Gio" "Application")
  (load-by-name "Gio" "ApplicationFlags")

  (for-each
   (cute load-by-name "Gtk" <>)
   '("TreeStore" "TreeModel" "TreeIter")))`

Which doesn't make it appear.

**Comment by LordYuuma** [comment]
You have a layer of brackets too many in your `use-typelibs` call, probably? Not sure if I went wrong with my syntax somewhere.

Try `(load-by-name "GLib" "markup_escape_text")`.

**Comment by daym** [comment]
Thanks! I tried removing the extra brackets, I get exactly the same error message (maybe I'm missing `use-typelibs` macro?).

The latter does work, thanks.

**Comment by LordYuuma** [comment]
`use-typelibs` should be exported by `(gi)`, so you should have it. If you have a MWE (please also try `macroexpand`ing it), open a separate issue for `use-typelibs`. I'll close this issue as the `g_markup` part seems to be resolved.

**Comment by daym** [comment]
Yes, that works just fine with `(load-by-name "GLib" "markup_escape_text")`.

If you are curious, check out `https://gitlab.com/daym/guix-gui/-/blob/30424ec705048218503f2840bbacfbecdcc75dd9/guixgui/manifests.scm` at the top for where and how I use it.

**Comment by LordYuuma** [comment]
A GUI for GNU Guix? You are a hero.

**Comment by daym** [comment]
Thanks!

Yeah, it has always bothered me that Guix doesn't have it. I mean distributions in 2005 had that :P

Then I remembered that I'm a programmer and that I can change that ;)

Even with my tiny preliminary gui I feel much better already: I can *see* the contents of a profile, and I can search for available packages.

Soon I'll be able to add and remove packages to the profile etc.
