### ISSUE TITLE
Storing guile function (or whatever) in a gtktreestore column

### ISSUE THREAD

**Issue by daym** [spk121/guile-gi#95]
It would be nice if one could store a guile function (or whatever) in a `GtkTreeStore` column.

**Comment by LordYuuma** [comment]
Perhaps you could try wrapping your procedure in a closure. IIRC all you'd need would be support for storing it in a GValue, no?

**Comment by daym** [comment]
Yes, storing it in a `GValue`. Do you mean `GClosure`? Is it supported in `guile-gi` to store a Guile procedure in a `GClosure` ?

**Comment by LordYuuma** [comment]
`(gi types)` should export `procedure->closure` if I'm not mistaken.

**Comment by daym** [comment]
Indeed, it works with that! Maybe I should read more `guile-gi` documentation--sorry.

**Comment by daym** [comment]
After having stored a procedure into a treeview cell like this, how do I get it back out so I can call it?

`procedure->closure` makes a `GClosure` which means I cannot return a guile function (in this case a guix `<package>` record) from my function.

Is there another way to store Guix `<package>`s into a tree?

**Comment by LordYuuma** [comment]
I don't think, that use case is currently supported.  You need to retrieve Guix records from the closure for further low-level processing, am I correct?  In other words, you can't restrict yourself to `GType`d structures here, can you?
