### ISSUE TITLE
container:get-children doesn't work

### ISSUE THREAD

**Issue by daym** [spk121/guile-gi#98]
(main.scm:19003): GuileGI-ERROR **: 19:16:38.914: unhandled argument type 'pointer to gpointer' src/gig_argument.c:1769

**Comment by LordYuuma** [comment]
I'm not sure, whether we have enough information to actually handle this meaningfully.  The real type would be `GList<GtkWidget*>*`, right?

**Comment by daym** [comment]
Yes.

C just doesn't have generics, so it cannot represent `GList<GtkWidget>`. Hence this weirdness.

**Comment by LordYuuma** [comment]
The thing with `GList` is, that it's not GType'd, so we have the GType `G_TYPE_POINTER` with an extra flag, that it's actually a list.

Can you enable debug messages and copy the arg map for `container:get-children` as it's being invoked?

**Comment by daym** [comment]
How?

**Comment by LordYuuma** [comment]
https://spk121.github.io/guile-gi/GLib-Logging.html#GLib-Logging

In essence, set `G_MESSAGES_DEBUG=all` and have fun with loads of messages.

**Comment by daym** [comment]
```
"CHANGED\n"(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442: container:get-children - calling with 1 input and 0 output arguments
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442: container:get-children - argument mapping
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442:  SCM inputs required: 0, optional: 0, outputs: 0
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442:  C inputs: 0, outputs: 0
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442:  Return: '%return' pointer to gpointer, output, singleton, required
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442:     Item Type: GtkWidget of type GObject
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442: [C2S] On line 1115 while handing pointer to gpointer of container:get-children.
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442: [C2S] On line 1795 while handing pointer to gpointer of container:get-children.
(guix-gui.in:21534): GuileGI-DEBUG: 14:08:55.442: [C2S] On line 1682 while handing pointer to gpointer of container:get-children.
```

**Comment by LordYuuma** [comment]
Ahh, I think that makes more sense. The 'pointer to gpointer' is misleading here, what's not handled is the non-pointer GObject item type.

**Comment by daym** [comment]
I'm pretty sure the list actually contains pointers to GtkWidget.

**Comment by LordYuuma** [comment]
Hmm, if that's the case, then perhaps the return type is incorrectly annotated? Wouldn't be the first broken gir.

**Comment by daym** [comment]
Maybe--but I have you a list of the types used in the gir, above (it was retrieved using grep). So that's how they look.

**Comment by LordYuuma** [comment]
The thing is, our conversion handles either basic types or pointers to objects. We don't really have a way of unpacking plain types into lists.  That wouldn't even work, as `sizeof(obj) != sizeof(void*)` in most of those cases, I assume.

**Comment by daym** [comment]
Yes, and upstream also only supports `GList<int>` and all others seem to have a forced star at `GList<T*>`

**Comment by daym** [comment]
Thanks.

But I think the g_warning is overdoing it. *Almost all* the element types in gobject-introspection, glib and gtk (see above) are specified without `*` but the `*` is implied.

**Comment by LordYuuma** [comment]
I think at least some warning should be given when two cases are treated the same.  Furthermore, it makes sense to warn on the implicit pointer, since other data structures (see GLib.Array) have explicit pointers as well and the argument handler assumes those pointers to be explicit.  (The reason we have that is mostly historical; Grilo used – and probably still uses – explicit pointers at the time of writing that code.)  If that turns out to in fact be a well-documented feature of GI, we'll retract the warning, but for now it's better to keep it.  The standard output of Gtk apps is not intended to be looked at anyway.

**Comment by daym** [comment]
The problem is that I can't use `--g-fatal-warnings` in order to find real problems anymore.

Please ask `gobject-introspection` maintainers on how to handle this in order to be sure, and then we don't need to `g_warning` anymore.

**Comment by LordYuuma** [comment]
Guile-GI does not play nice with fatal warnings anyway.  Loading Gtk already raises some pointer warnings before that.  I'd rather recommend using our custom loggers to filter warnings coming from GLib/Gtk etc. and bail on them.  Alternatively, you are free to patch out the warning on your end.

**Comment by daym** [comment]
Fine.

But asking for the right way should still be done :+1:
